### ISSUE TITLE
QuickerBB 0.7.0 - Register Cross Site Scripting Vulnerability

### ISSUE THREAD

**Issue by fgeek** [halojoy/QuickerBB#9]
Original advisory in full-disclosure mailing list: http://seclists.org/fulldisclosure/2016/Aug/48

I have not verified this issue by myself. Do you have plans to fix this vulnerability?

**Comment by halojoy** [comment]
I may look into this.
But right now I am short of time.
Thanks for bothering with this issue.
halojoy

**Comment by halojoy** [comment]
Well, I use **PDO::prepare** and then PDO::execute
to insert **username, email** and the rest of the data into database.
According to PHP manual this reduces risc of X-side scripting.

If this is not enough I can put htmlspecialchars() around the posted input.
But I want to know more before changing my register.php

Thanks from halojoy
